name: Build

on:
  workflow_dispatch: 
  push:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish -c Release --output /home/runner/work/Testably.Server/Testably.Server/publish/ Source/Testably.Server/Testably.Server.csproj
    - name: Shutdown webpage
      shell: pwsh
      run: |
        $response = try { 
          (Invoke-WebRequest -Uri https://testably.org/lifetime/quit -Method POST -ErrorAction Stop).BaseResponse
          Write-Information "The server was shutdown"
        } catch [System.Net.WebException] { 
          Write-Warning "An exception was caught: $($_.Exception.Message)"
          $_.Exception.Response 
        }
        Start-Sleep -Seconds 5
    - name: Upload ftp
      uses: sebastianpopp/ftp-action@releases/v2
      with:
        host: ftps://access938340810.webspace-data.io:990
        user: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        localDir: /home/runner/work/Testably.Server/Testably.Server/publish/
        remoteDir: "."
